# Controller
/*/controller:
  ros__parameters:
    crazyradio_driver:
      enable: False
      crazyflie_names:
        - crazy_jirl_bl
        - crazy_jirl_bl2
      crazyradio_uris:
        - radio://0/80/2M/E7E7E7E7B1
        - radio://0/80/2M/E7E7E7E7B3
      ext_driver: py   # cpp or python
    gate_side: 1.0
    low_level_controller:
      c1: -0.6709
      c2: 0.1932
      c3: 13.0652
      thrust_pwm_min: 10001
      thrust_pwm_max: 50000
    policy:
      # path: /home/neo/workspace/logs/policies/2025-06-18_15-28-43/model_3200_13022.pt   # half working
      # path: /home/neo/workspace/logs/policies/2025-06-20_15-19-30/model_750_8215.pt
      path: /home/neo/workspace/logs/policies/2025-06-21_19-31-24/best_model.pt
      # path: /home/neo/workspace/logs/policies/2025-06-27_00-31-59/best_model.pt
      waypoints: [
         0.0, 3.0, 0.75, 0.0, 0.0,  0.0,
        -1.5, 4.5, 0.75, 0.0, 0.0, -1.57,
         0.0, 6.0, 1.75, 0.0, 0.0,  3.14,
         1.5, 4.5, 0.75, 0.0, 0.0,  1.57
      ]
      initial_waypoint: 0
    takeoff_height: 0.5

# Crazyradio driver
/crazyradio_driver:
  ros__parameters:
    crazyflie_names:
      - crazy_jirl_bl
      - crazy_jirl_bl2
    crazyradio_uris:
      - radio://0/80/2M/E7E7E7E7B1
      - radio://0/80/2M/E7E7E7E7B3
    logger_period_ms: 1000
    reconnection_period_ms: 2000

# Vicon
/vicon_node:
  ros__parameters:
    server_address: mocap.perch
    frame_rate: 120
    max_accel: 10.0
    publish_tf: true
    publish_pts: false
    fixed_frame_id: mocap
    timer_single_pub_freq: 100
    timer_multi_pub_freq: 100
    model_list:
      - crazy_jirl_bl
      - crazy_jirl_bl2
