# Controller
/*/controller:
  ros__parameters:
    low_level_controller:
      c1: -0.6709
      c2: 0.1932
      c3: 13.0652
      thrust_pwm_min: 10001
      thrust_pwm_max: 60000
    policy:
      enable: false
      path: /home/neo/workspace/logs/policies/2025-03-04_01-02-56/model_4999.pt
    takeoff_height: 1.0

# Crazyradio driver
/crazyradio_driver:
  ros__parameters:
    crazyflie_names: [
      # crazy_jirl_01,
      crazy_jirl_02,
      # crazy_jirl_03,
      # crazy_jirl_05,
      # crazy_jirl_01_demo
    ]
    crazyradio_uris: [
      # radio://0/80/2M/E7E7E70101,
      radio://0/81/2M/E7E7E70102,
      # radio://0/115/2M/E7E7E7E703,
      # radio://0/50/2M/E7E7E7E705,
      # radio://0/110/2M/E7E7E7E701,
    ]
    logger_period_ms: 1000
    reconnection_period_ms: 2000

# Vicon
/mocap_vicon_node:
  ros__parameters:
    server_address: mocap.perch
    frame_rate: 120
    max_accel: 10.0
    publish_tf: true
    publish_pts: false
    fixed_frame_id: mocap
    timer_pub_freq: 50
    model_list:
      - crazy_jirl_01
      - crazy_jirl_02
      - crazy_jirl_03
      - crazy_jirl_05
      - crazy_jirl_01_demo